version: '3.1'

services:

  # Database service
  db:
    image: mysql:latest
    container_name: wordpressdb    
    restart: unless-stopped
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]    
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  # WordPress service
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress-app    
    restart: unless-stopped    
    volumes:
      - wordpress_data:/var/www/html
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    ports:
      - "8082:80"
      - "8443:443"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

volumes:
  dbdata:
  wordpress_data:
